Support nested fields and arrays
react-component/form pull request #48
Opened 2016-12-18 17:14 UTC by williamkhshea

See #47 

In input form

```
{getFieldDecorator('member[0].name.firstname', {})(<input/>)}
{getFieldDecorator('member[1].name.firstname', {})(<input/>)}
```

this.props.form.getFieldsValue() 返回数据结构为
```
members: [{ name: {firstname: "xxx"} }, { name: {firstname: "yyy"} }]
```

2016-12-19 02:10 UTC, alexggordon commented
@williamkhshea just saw this. Upon validate, does this also return the same nested object?

IE, on submit, will it return 

```
{member: [
     {name: {firstname: 'fdsafdsa'}},
     {name: {firstname: 'firstname_two'}}
]}
```

If it's doing this, then I'll close my PR in favor of this one.

2016-12-19 02:21 UTC, williamkhshea commented
@alexggordon Yes, and errors will be nested object as well.

I have added an example called "nested-field" in the example folder. You can check it out and see what how the outputs look like.

2016-12-19 03:07 UTC, alexggordon commented
Sweet job @williamkhshea.

2016-12-19 03:19 UTC, afc163 commented
:+1:

2016-12-19 10:27 UTC, yiminghe requested changes

2016-12-19 10:27 UTC, yiminghe commented on package.json
> +    "lodash": "^4.17.2",
do not use lodash(especially too big for mobile), or at least use lodash-xx

2016-12-19 20:50 UTC, williamkhshea commented on package.json
> +    "lodash": "^4.17.2",
@yiminghe OK, I will update to use custom build of lodash

2016-12-19 22:00 UTC, williamkhshea commented
@yiminghe How can I ignore the lint style checking for the lodash custom build file before I commit?

2016-12-20 06:34 UTC, yiminghe commented
I mean something like https://www.npmjs.com/package/lodash.get

2016-12-21 18:14 UTC, williamkhshea commented
@yiminghe Dependencies updated. Please review.

2016-12-22 03:42 UTC, afc163 commented
Use https://github.com/mariocasciaro/object-path ?

2016-12-22 04:14 UTC, williamkhshea commented
@afc163 Object-path uses only dot notation for array path (i.e. 'a.0'), unlike lodash which also supports bracket notation (i.e. 'a[0]'). It creates problems when you want to have numbers as keys of an object, says in case of IDs. It gives you an array instead of object with keys as IDs.

If you want to trim down the size of the libraries further, I would suggest you do a custom build on lodash get,has,set function and make an npm package, and I can use it as dependencies.

2016-12-22 06:16 UTC, yiminghe requested changes
last change. please squash into one commit. ready to merge


thank you

2016-12-22 06:16 UTC, yiminghe commented on tests/overview.spec.js
> +    expect(isEqual(form.getFieldValue('foo'), {
expect(form.getFieldValue('foo')).to.eql({....})

2016-12-22 08:18 UTC, williamkhshea commented on tests/overview.spec.js
> +    expect(isEqual(form.getFieldValue('foo'), {
@yiminghe expect(...).to.eql does not handle sparse arrays (e.g. [undefined, 123]). See screenshot below.

![2016-12-22 16_15_58-will s imac - teamviewer - free license non-commercial use only](https://cloud.githubusercontent.com/assets/4775489/21419347/07949b7e-c862-11e6-8ade-f47ee0c3f82d.png)

2016-12-22 09:09 UTC, yiminghe commented on tests/overview.spec.js
> +    expect(isEqual(form.getFieldValue('foo'), {
ok, squash into one commit, and force push please

2016-12-26 10:07 UTC, williamkhshea commented on tests/overview.spec.js
> +    expect(isEqual(form.getFieldValue('foo'), {
@yiminghe done

2016-12-28 10:20 UTC, merged

2016-12-28 12:43 UTC, williamkhshea commented
@yiminghe I should have cleaned up my code before submitting. Thanks for helping out.

2017-03-20 07:23 UTC, acmeid commented
我在使用嵌套写法的时候，并没有生效：
```
<FormItem label="数量" colon={false}>
  {getFieldDecorator('services[0].num', {
      rules: [{ required: true, message: '请输入数量' }],
   })(
      <InputNumber />
   )}
</FormItem>

services: [{
    num: {value: 1}
}]
```

2017-04-23 19:07 UTC, mkrn commented
@williamkhshea Can this bug be related to this PR? 
https://github.com/ant-design/ant-design/issues/5835
Can you please give me a hint if you have this situation working (array of objects)

2018-03-08 07:38 UTC, nanxiaobei commented
then setFieldsValue not work with nested assign, anyone know how to solve?

2018-03-08 09:25 UTC, benjycui commented
@nanxiaobei please file a new issue and provide re-producible demo http://codepen.io/benjycui/pen/NdQdBw?editors=0011

2018-08-29 07:19 UTC, warmhug commented
`isFieldTouched` seems also not work with nested.

2019-09-26 09:09 UTC, zhangpeng11 commented
我注释掉getFieldValue这种代码以后神奇的就变回数组了，这是什么情况

2019-12-12 15:46 UTC, jarforjs commented
> then setFieldsValue not work with nested assign, anyone know how to solve?

me too,then i use setFiledsValue(()=>{setTimeout...}),Nevertheless, it seems to be successful, but there are still problems

2020-06-16 06:03 UTC, 17601617393 commented
> 参见[＃47](https://github.com/react-component/form/issues/47)
> 
> 输入形式
> 
> ```
> {getFieldDecorator('member[0].name.firstname', {})(<input/>)}
> {getFieldDecorator('member[1].name.firstname', {})(<input/>)}
> ```
> 
> this.props.form.getFieldsValue（）返回数据结构为
> 
> ```
> members: [{ name: {firstname: "xxx"} }, { name: {firstname: "yyy"} }]
> ```
id再转一下string类型就OK了

2022-05-21 09:55 UTC, Jiang-Xuan commented
如果有人想要 key 里面含有 . 的话, 参考 https://github.com/lodash/lodash/issues/3529#issuecomment-448586433

2023-05-19 08:44 UTC, pkuphy commented
楼上的方法可以，效果是这样的：

`getFieldDecorator('["user.name"]', ...`

![Screenshot-2023-05-19_16_43_22](https://github.com/react-component/form/assets/3149388/c80eed76-51fe-4956-80f8-533f227700ca)